### ISSUE TITLE
Feature Request: DonorDashboardSummary queries should deal with `no index found` 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#373] opened 2021-03-02 16:14 UTC
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/KIM2-GB/dashboard

In the donor summary query, if an index is missing, then the API returns an error like this: 
![image](https://user-images.githubusercontent.com/15824252/109567297-2301fe80-7ab3-11eb-9211-010521acfcfa.png)

## How to Reproduce
From the dev platform api: https://argo-gateway.dev.argo.cancercollaboratory.org/graphql
```
query {
  programDonorSummaryEntries(programShortName:"TEST-PR"){
    sangerVcsFailed
    sangerVcsRunning
    mutectFailed
    mutectRunning
    mutectCompleted
  }
}
```
Error: 
```
 "message": "Cannot return null for non-nullable field DonorSummaryEntry.sangerVcsFailed.",
```

## Expected Behaviour 
Should either report that there is no index, or all (0) rather than the errors.

**Comment by Buwujiu** [comment] 2021-06-14 22:38
Investigated the issue and found that the cause of the error is not because of index not found, the cause is when the non-null graphql api field (in this case, the field is one of these:  
   sangerVcsFailed
    sangerVcsRunning
    mutectFailed
    mutectRunning
    mutectCompleted
)
is missing in elasticsearch index, graphql throws error because it's expecting a value, but because these fields were not implemented in the index yet, error was thrown. 

Right now since all fields are populated in es index, gateway api will not throw any errors. No code change is needed, but as a future note, if we are adding more fields into the api, especially when fields are null-able, they should be marked as non-null in graphql schema.

**Comment by rosibaj** [comment] 2021-06-17 14:46
- Add a SOP + wiki on adding to the aggregator 
-

**Closed** 2021-07-08 17:11 UTC
Labels: new-feature
